version: "3.8"

services:
  # backend:
  #   build: 
  #     context: ./backend
  #   command: startApi
  #   ports:
  #     - 8000:8000
  #   environment:
  #     - KAFKA_URL=kafka:9092
  #   volumes:
  #     - type: bind
  #       source: ./backend
  #       target: /app

  # model_matcher:
  #   build: 
  #     context: ./model_matcher
  #   command: startModel
  #   volumes:
  #     - type: bind
  #       source: ./model_matcher
  #       target: /app

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - 6379:6379
