version: "3.8"

services:
  backend:
    build:
      context: ./backend
    command: startApi
    ports:
      - 8000:8000
    environment:
      - KAFKA_SERVER_IP=kafka
      - KAFKA_SERVER_PORT=9092
      - KAFKA_INPUT_TOPIC=input_topic
      - KAFKA_OUTPUT_TOPIC=out_topic
      - REDIS_SERVER_IP=redis
      - REDIS_SERVER_PORT=6379
      - REDIS_SERVER_DB=0
    depends_on:
      - kafka
      - redis

  model_matcher:
    build:
      context: ./model_matcher
    command: startModel
    environment:
      - KAFKA_SERVER_IP=kafka
      - KAFKA_SERVER_PORT=9092
      - KAFKA_INPUT_TOPIC=input_topic
      - KAFKA_OUTPUT_TOPIC=out_topic
      - REDIS_SERVER_IP=redis
      - REDIS_SERVER_PORT=6379
      - REDIS_SERVER_DB=0
    depends_on:
      - kafka
      - redis

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - 6379:6379
